feat/updated-entity-questions
gamaacademy-labs/assesment-api pull request #22
Opened 2022-08-24 14:28 UTC by MateusMaciel340

Adicionando um array de objetos em questions (campo alternativa), foi com ausência pela branch de apresentar avaliações e questões.

2022-08-24 14:31 UTC, alvaroaxsmith approved these changes
lgtm

2022-08-26 11:53 UTC, sampaiorafael requested changes

2022-08-26 11:53 UTC, sampaiorafael commented on src/db/seeds/02-questions.seed.ts
> +          { alternativeId: 1, answer: 'answer1'},
Como já está dentro do array alternatives, a chave pode só se chamar id mesmo, e precisamos de uma chave isCorrect pra dizer qual é a resposta correta, e answer se refere a resposta, faria sentido se fosse a resposta do usuário, na alternativa esse nome não é muito descritivo

2022-08-26 21:19 UTC, sampaiorafael requested changes

2022-08-26 21:19 UTC, sampaiorafael commented on src/db/migrations/1661524560607-add_questions.ts
> +export class addQuestions1661524560607 implements MigrationInterface {
Ta tudo correto, o unico problema é a migration, não se deve nunca alterar uma migration que já foi rodada em ambiente de produção, quando eu peço pra voces alterarem é que ela ainda está em development, eai de boa. Depois que rodamos em produção, ela fica registrada, e o timestamp tambem. O correto nesse caso, seria simplesmente alterar a entidade e gerar uma nova migration com typeorm:migration:generate que ele ia gerar uma migration alterando a entidade usando o ALTER TABLE do SQL ao inves de alterar uma migration já existente. Só isso pro pr ser aprovado.

2022-08-27 11:42 UTC, MateusMaciel340 commented on src/db/migrations/1661524560607-add_questions.ts
> +export class addQuestions1661524560607 implements MigrationInterface {
Corrigido.

2022-08-29 17:36 UTC, sampaiorafael approved these changes

2022-08-29 17:36 UTC, merged