Feat/assessment module
gamaacademy-labs/assesment-api pull request #7
Opened 2022-08-17 03:30 UTC by alvaroaxsmith

criação do module e controller do assessment.

2022-08-17 14:10 UTC, sampaiorafael requested changes

2022-08-17 14:10 UTC, sampaiorafael commented on src/modules/assessment/assessment.controller.ts
> +        const assessment = await this.findAssessmentById(id)
Controller ta como recursivo, ele chama ele mesmo na linha 11

2022-08-17 16:58 UTC, MateusMaciel340 approved these changes
lgtm

2022-08-18 14:12 UTC, sampaiorafael approved these changes

2022-08-18 14:30 UTC, merged